---
title: "Class Prep 5 | 2.3.2 - 2.3.3"
author: "Riley Primeau"
date: '`r Sys.Date()`'
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Section 2.3.2 Loss of Significance

```{r}
1/3 - .33333333333333
1 - .999999999999
(1 - .999999999999) * 1000

20.55 - 19.2 - 1.35
20.55 - 1.35 - 19.2
```

```{r}
quadratic = function(b2, b1, b0){
  t1 = sqrt(b1^2 - 4 * b2 * b0)
  t2 = 2*b2
  
  x1 = -(b1 + t1)/t2
  x2 = -(b1 - t1)/t2
  return(c(x1, x2))
}

quadratic2 = function(b2, b1, b0)
{
  t1 = sqrt(b1^2 - 4 * b2 * b0)
  t2 = 2*b0
  
  x1 = t2/(-b1 - t1)
  x2 = t2/(-b1 + t1)
  return(c(x2, x1))
}

```

```{r}
b2 = 94906265.625
b1 = 189812534.000
b0 = 94906268.375
print(quadratic(b2, b1, b0), digits = 20)

print(quadratic2(b2, b1, b0), digits = 20)
```

## Section 2.3.3 Overflow and Underflow

There is one typo in this section where the author does not do the same calculations with the integer and double precision numbers.  
```{r}
.Machine$double.xmin
.Machine$double.xmin/2

.Machine$double.xmax

2147483647L * 2L
2147483647* 2

.Machine$double.xmax * 2
```

