---
title: "Class Prep 7 | 3.1.2 - 3.2.1"
author: "Riley Primeau"
date: '`r Sys.Date()`'
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Section 3.1.2 Elementary Row Operations

```{r}
scalerow = function(m, row, k){
  m[row,] = m[row,] * k
  return(m)
}

swaprows = function(m, row1, row2){
  row.tmp = m[row1,]
  m[row1,] = m[row2,]
  m[row2,] = row.tmp
  
  return(m)
}
```

```{r}
A = matrix(1:15, 5)
scalerow(A, 2, 10)
```

```{r}
replacerow = function(m, row1, row2, k){
  m[row2,] = m[row2,] + m[row1,] * k
  return(m)
}
```

```{r}
swaprows(A, 1, 4)
replacerow(A, 1, 3, -3)
```


## Section 3.2.1 Row Echelon Form

```{r}
refmatrix = function(m){
  count.rows = nrow(m)
  count.cols = ncol(m)
  piv = 1
  
  for(row.curr in 1:count.rows){
    if(piv <= count.cols){
      i = row.curr
      while(m[i, piv] == 0 && i < count.rows){
        i = i + 1
        if(i > count.rows){
          i = row.curr
          piv = piv + 1
          if(piv > count.cols)
            return(m)
        }
      }
      if (i != row.curr)
        m = swaprows(m, i, rows.curr)
      for(j in row.curr:count.rows)
        if(j != row.curr){
          k = m[j, piv] / m[row.curr, piv]
          m = replacerow(m, row.curr, j, -k)
        }
      piv = piv + 1
    }
  }
  return(m)
}
```

```{r}
(A = matrix(c(5, 5, 5, 8, 2, 2, 6, 5, 4), 3))
refmatrix(A)

(A = matrix(c(2, 4, 2, 4, 9, 4, 3, 6, 7, 7, 3, 9), 3))
refmatrix(A)

(A = matrix(c(2, 8, 5, 5, 1, 2, 3, 8, 4), 3))
refmatrix(A)
```

```{r}
rrefmatrix = function(m){
  count.rows = nrow(m)
  count.cols = ncol(m)
  piv = 1
  
  for(row.curr in 1:count.rows){
    if(piv <= count.cols){
      i = row.curr
      while(m[i, piv] == 0 && i < count.rows){
        i = i + 1
        if(i > count.rows){
          i = row.curr
          piv = piv + 1
          if(piv > count.cols)
            return(m)
        }
      }
      if (i != row.curr)
        m = swaprows(m, i, rows.curr)
      piv.val = m[row.curr, piv]
      m = scalerow(m, row.curr, 1 / piv.val)
      for(j in 1:count.rows)
        if(j != row.curr){
          k = m[j, piv] / m[row.curr, piv]
          m = replacerow(m, row.curr, j, -k)
        }
      piv = piv + 1
    }
  }
  return(m)
}
```

```{r}
A = matrix(c(5, 5, 5, 8, 2, 2, 6, 5, 4), 3)
rrefmatrix(A)

A = matrix(c(2, 4, 2, 4, 9, 4, 3, 6, 7, 7, 3, 9), 3)
rrefmatrix(A)

A = matrix(c(2, 8, 5, 5, 1, 2, 3, 8, 4), 3)
rrefmatrix(A)


(A = matrix(c(2, 3, 1, 1, 2, -5, -1, -2, 4), 3))
(b = c(1, 1, 3))

rrefmatrix(cbind(A, b))
```

```{r}
solvematrix = function(A, b){
  m = cbind(A, b)
  m = rrefmatrix(m)
  x = m[, ncol(m)]
  
  return(x)
}

solvematrix(A, b)
solve(A, b)
```


